cuda: false
deterministic: true
log:
  huggingface:
    entity: null
    upload: false
  run_name: __init__
  save: false
  video: false
  wandb:
    entity: null
    project: test
    tags: []
    track: false
seed: 0
training:
  agent:
    batch_size: 256
    buffer_size: 1000000.0
    gamma: 0.99
    learning_rate: 0.0003
    noise_clip: 0.5
    policy_noise: 0.1
    policy_update: 128
    start_learning: 100
    tau: 0.005
  optimizer:
    gene_mutation_prob: 0.05
    n_generations: 10
    n_genomes: 12
    n_individuals: 10
    n_parents_mating: 2
    program:
      max_node_arity: 2
      n_nodes: 6
      representation: Cartesian
